[16:48:29] [DEBUG] Running client sanity checks...
[16:48:29] [DEBUG] Loaded Extension: interactions.ext.jurigged
[16:48:30] [DEBUG] No setup function found in play
[16:48:30] [DEBUG] Found extension class Music in play: Attempting to load
[16:48:30] [DEBUG] Added callback: Music._menu
[16:48:30] [DEBUG] Added callback: Music._pause
[16:48:30] [DEBUG] Added callback: Music._resume
[16:48:30] [DEBUG] Added callback: Music._skip
[16:48:30] [DEBUG] Added callback: Music._stop
[16:48:30] [DEBUG] Added callback: Music.play
[16:48:30] [DEBUG] Loaded Extension: play
[16:48:30] [DEBUG] No setup function found in askbard
[16:48:30] [DEBUG] Found extension class Bard in askbard: Attempting to load
[16:48:30] [DEBUG] Added callback: Bard._askbard
[16:48:30] [DEBUG] Added callback: Bard._endbard
[16:48:30] [DEBUG] Added callback: Bard.set_bard_channel
[16:48:30] [DEBUG] Loaded Extension: askbard
[16:48:30] [DEBUG] No setup function found in noi_chu
[16:48:30] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[16:48:30] [DEBUG] Added callback: NoiChu._reset
[16:48:30] [DEBUG] Added callback: NoiChu._world_setup
[16:48:30] [DEBUG] Loaded Extension: noi_chu
[16:48:30] [DEBUG] No setup function found in db_refesh
[16:48:30] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[16:48:30] [DEBUG] Loaded Extension: db_refesh
[16:48:30] [DEBUG] No setup function found in help
[16:48:30] [DEBUG] Found extension class Help in help: Attempting to load
[16:48:30] [DEBUG] Added callback: Help._about
[16:48:30] [DEBUG] Added callback: Help.help
[16:48:30] [DEBUG] Loaded Extension: help
[16:48:30] [DEBUG] No setup function found in channel_listen
[16:48:30] [DEBUG] Found extension class ChannelListen in channel_listen: Attempting to load
[16:48:30] [DEBUG] Added callback: ChannelListen._setup
[16:48:30] [DEBUG] Loaded Extension: channel_listen
[16:48:30] [DEBUG] Added callback: on_start
[16:48:30] [DEBUG] 1 callbacks have been loaded from __main__.
[16:48:30] [DEBUG] Added callback: _disconnect
[16:48:30] [DEBUG] Added callback: _on_websocket_ready
[16:48:30] [DEBUG] Added callback: on_autocomplete_completion
[16:48:30] [DEBUG] Added callback: on_autocomplete_error
[16:48:30] [DEBUG] Added callback: on_command_completion
[16:48:30] [DEBUG] Added callback: on_command_error
[16:48:30] [DEBUG] Added callback: on_component_completion
[16:48:30] [DEBUG] Added callback: on_component_error
[16:48:30] [DEBUG] Added callback: on_error
[16:48:30] [DEBUG] Added callback: on_modal_completion
[16:48:30] [DEBUG] Added callback: on_modal_error
[16:48:30] [DEBUG] Added callback: on_resume
[16:48:30] [DEBUG] 12 callbacks have been loaded from Client.
[16:48:30] [DEBUG] Attempting to login
[16:48:31] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[16:48:31] [DEBUG] GET /users/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[16:48:31] [DEBUG] GET /users/@me Received 200 :: [0/1000 calls remaining]
[16:48:31] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[16:48:31] [DEBUG] GET /oauth2/applications/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[16:48:31] [DEBUG] GET /oauth2/applications/@me Received 200 :: [0/1000 calls remaining]
[16:48:31] [WARNING] Setting sync_ext to True by default for syncing changes
[16:48:31] [INFO] Loading jurigged
[16:48:31] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\Main.py
[16:48:31] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\play.py
[16:48:31] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\embed.py
[16:48:31] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\askbard.py
[16:48:31] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\noi_chu.py
[16:48:31] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\db_refesh.py
[16:48:31] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\help.py
[16:48:31] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\channel_listen.py
[16:48:31] [DEBUG] Caching ingested rate limit data for: 0a6d458104b103c7be293cc9b284d9ee
[16:48:31] [DEBUG] GET /gateway Received 200 :: [99/100 calls remaining]
[16:48:31] [INFO] Shard ID 0 | Starting Shard
[16:48:31] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[16:48:31] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[16:48:32] [INFO] Shard ID 0 | Gateway connection established
[16:48:32] [DEBUG] Shard ID 0 | Session ID: ea0f569d755808bea466b2c733aa537f Trace: ['["gateway-prd-us-east1-d-5b7w",{"micros":90930,"calls":["id_created",{"micros":1429,"calls":[]},"session_lookup_time",{"micros":387,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-prd-2-174",{"micros":87084,"calls":["start_session",{"micros":57807,"calls":["discord-api-6c869fb97d-zxt9w",{"micros":52927,"calls":["get_user",{"micros":10415},"get_guilds",{"micros":6062},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":846},"authorized_ip_coro",{"micros":17}]}]},"starting_guild_connect",{"micros":79,"calls":[]},"presence_started",{"micros":389,"calls":[]},"guilds_started",{"micros":170,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":28611,"calls":[]},"connect_finished",{"micros":28617,"calls":[]},"build_ready",{"micros":18,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']
[16:48:32] [DEBUG] Dispatching Event: websocket_ready
[16:48:32] [DEBUG] Dispatching Event: guild_join
[16:48:32] [DEBUG] Dispatching Event: guild_join
[16:48:32] [DEBUG] Dispatching Event: guild_join
[16:48:32] [DEBUG] Dispatching Event: guild_join
[16:48:32] [DEBUG] Dispatching Event: guild_join
[16:48:32] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[16:48:32] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[16:48:32] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[16:48:32] [DEBUG] Waiting for bucket dd84d9818020c27975c0d5ab4a794d44 to unlock.
[16:48:33] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[16:48:33] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[16:48:33] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[16:48:33] [DEBUG] 0 is already up-to-date with 14 commands.
[16:48:33] [DEBUG] Sync of 1 scopes took 0.7605540999793448 seconds
[16:48:33] [DEBUG] Dispatching Event: startup
[16:48:33] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1703756913152, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[16:48:34] [DEBUG] 1174695146214928500::play should be called
[16:48:35] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[16:48:35] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE4OTg2NzQ4Njc3MDkwNTEyOTo1YTQ1NDlrOUpHaEdvemkydHdEUDJiS3RuY3Q3UlhYR1N5Q0dHZ2ZPd2VmeVBqOGVvQVRaelZkQnBIZTZVUTRWTUNzRHdUSlJVcGlzdUlCc3pGVm5oazQxMmpuVTBqNnlqSHRBcWdHdmxhaU9TUjYzTGk1c2MwVnFWTkY0ejBTSw/callback Received 204 :: [4/5 calls remaining]
[16:48:35] [DEBUG] Sending data to websocket: {"op": 4, "d": {"guild_id": 1067024293709496340, "channel_id": 1189851990356918383, "self_mute": false, "self_deaf": false}}
[16:48:35] [DEBUG] Waiting for voice connection data...
[16:48:35] [DEBUG] Dispatching Event: message_create
[16:48:35] [DEBUG] Dispatching Event: voice_user_join
[16:48:35] [DEBUG] Attempting to initialise voice gateway...
[16:48:36] [DEBUG] Voice Connection has identified itself to Voice Gateway
[16:48:36] [DEBUG] Discord send VC Ready! Establishing a socket connection...
[16:48:36] [DEBUG] IP Discovery in progress...
[16:48:36] [DEBUG] Voice Initial Response Received: b'\x00\x02\x00F\x00\x05c\xa5116.100.183.123\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfbN'
[16:48:36] [DEBUG] IP Discovered: 116.100.183.123 #64334
[16:48:36] [DEBUG] Sending data to websocket: {"op": 1, "d": {"protocol": "udp", "data": {"address": "116.100.183.123", "port": 64334, "mode": "xsalsa20_poly1305_lite"}}}
[16:48:36] [DEBUG] Starting UDP Keep Alive
[16:48:36] [DEBUG] Unhandled OPCODE: 18 = data = {'user_id': '610841389164396565', 'flags': 2}
[16:48:36] [DEBUG] Unhandled OPCODE: 20 = data = {'user_id': '610841389164396565', 'platform': 0}
[16:48:36] [INFO] Voice connection established; using xsalsa20_poly1305_lite
[16:48:37] [DEBUG] Dispatching Event: command_error
[16:48:37] [DEBUG] Dispatching Event: command_completion
[16:48:37] [DEBUG] Dispatching Event: error
[16:48:37] [INFO] Command Called: play with event.ctx.args = ['https://www.youtube.com/playlist?list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD'] | event.ctx.kwargs = {'song': 'https://www.youtube.com/playlist?list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD'}
[16:48:37] [ERROR] Ignoring exception in cmd `/play`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\play.py", line 132, in play
    await music_queues.playlist_process(url_list)
  File "D:\Project\Python\qpneruy-Git\modules\Music_queue.py", line 40, in playlist_process
    self.put(song)
  File "D:\Project\Python\qpneruy-Git\modules\Music_queue.py", line 43, in put
    title = audio_d.entry['title']
            ^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'entry'

[16:48:40] [DEBUG] Sending heartbeat every 13.75 seconds
[16:48:40] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.3565284845865947}
[16:48:40] [DEBUG] ❤ Voice Connection is sending Heartbeat
[16:48:40] [DEBUG] ❤ Heartbeat acknowledged after 0.09220 seconds
[16:48:45] [DEBUG] Sending heartbeat every 41.25 seconds
[16:48:45] [DEBUG] Sending data to websocket: {"op": 1, "d": 10}
[16:48:45] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[16:48:45] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[16:48:53] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.18308212304541627}
[16:48:53] [DEBUG] ❤ Voice Connection is sending Heartbeat
[16:48:54] [DEBUG] ❤ Heartbeat acknowledged after 0.10050 seconds
[16:49:01] [DEBUG] Dispatching Event: disconnect
[16:49:01] [DEBUG] Stopping the bot.
[16:49:01] [INFO] Shard ID 0 | Stopping Shard
