[21:23:10] [DEBUG] Running client sanity checks...
[21:23:10] [DEBUG] Loaded Extension: interactions.ext.jurigged
[21:23:10] [DEBUG] No setup function found in play
[21:23:10] [DEBUG] Found extension class Music in play: Attempting to load
[21:23:10] [DEBUG] Added callback: Music._menu
[21:23:10] [DEBUG] Added callback: Music._pause
[21:23:10] [DEBUG] Added callback: Music._resume
[21:23:10] [DEBUG] Added callback: Music._skip
[21:23:10] [DEBUG] Added callback: Music._stop
[21:23:10] [DEBUG] Added callback: Music._viewplaylist
[21:23:10] [DEBUG] Added callback: Music.play
[21:23:10] [DEBUG] Loaded Extension: play
[21:23:11] [DEBUG] No setup function found in askbard
[21:23:11] [DEBUG] Found extension class Bard in askbard: Attempting to load
[21:23:11] [DEBUG] Added callback: Bard._askbard
[21:23:11] [DEBUG] Added callback: Bard._endbard
[21:23:11] [DEBUG] Added callback: Bard.set_bard_channel
[21:23:11] [DEBUG] Loaded Extension: askbard
[21:23:11] [DEBUG] No setup function found in noi_chu
[21:23:11] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[21:23:11] [DEBUG] Added callback: NoiChu._reset
[21:23:11] [DEBUG] Added callback: NoiChu._world_setup
[21:23:11] [DEBUG] Loaded Extension: noi_chu
[21:23:11] [DEBUG] No setup function found in db_refesh
[21:23:11] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[21:23:11] [DEBUG] Loaded Extension: db_refesh
[21:23:11] [DEBUG] No setup function found in help
[21:23:11] [DEBUG] Found extension class Help in help: Attempting to load
[21:23:11] [DEBUG] Added callback: Help._about
[21:23:11] [DEBUG] Added callback: Help.help
[21:23:11] [DEBUG] Loaded Extension: help
[21:23:11] [DEBUG] No setup function found in channel_listen
[21:23:11] [DEBUG] Found extension class ChannelListen in channel_listen: Attempting to load
[21:23:11] [DEBUG] Added callback: ChannelListen._setup
[21:23:11] [DEBUG] Loaded Extension: channel_listen
[21:23:11] [DEBUG] Added callback: on_start
[21:23:11] [DEBUG] 1 callbacks have been loaded from __main__.
[21:23:11] [DEBUG] Added callback: _disconnect
[21:23:11] [DEBUG] Added callback: _on_websocket_ready
[21:23:11] [DEBUG] Added callback: on_autocomplete_completion
[21:23:11] [DEBUG] Added callback: on_autocomplete_error
[21:23:11] [DEBUG] Added callback: on_command_completion
[21:23:11] [DEBUG] Added callback: on_command_error
[21:23:11] [DEBUG] Added callback: on_component_completion
[21:23:11] [DEBUG] Added callback: on_component_error
[21:23:11] [DEBUG] Added callback: on_error
[21:23:11] [DEBUG] Added callback: on_modal_completion
[21:23:11] [DEBUG] Added callback: on_modal_error
[21:23:11] [DEBUG] Added callback: on_resume
[21:23:11] [DEBUG] 12 callbacks have been loaded from Client.
[21:23:11] [DEBUG] Attempting to login
[21:23:11] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[21:23:11] [DEBUG] GET /users/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[21:23:11] [DEBUG] GET /users/@me Received 200 :: [0/1000 calls remaining]
[21:23:12] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[21:23:12] [DEBUG] GET /oauth2/applications/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[21:23:12] [DEBUG] GET /oauth2/applications/@me Received 200 :: [0/1000 calls remaining]
[21:23:12] [WARNING] Setting sync_ext to True by default for syncing changes
[21:23:12] [INFO] Loading jurigged
[21:23:12] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\Main.py
[21:23:12] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\play.py
[21:23:12] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\embed.py
[21:23:12] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\askbard.py
[21:23:12] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\noi_chu.py
[21:23:12] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\db_refesh.py
[21:23:12] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\help.py
[21:23:12] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\channel_listen.py
[21:23:12] [DEBUG] Caching ingested rate limit data for: 0a6d458104b103c7be293cc9b284d9ee
[21:23:12] [DEBUG] GET /gateway Received 200 :: [99/100 calls remaining]
[21:23:12] [INFO] Shard ID 0 | Starting Shard
[21:23:12] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[21:23:12] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[21:23:13] [INFO] Shard ID 0 | Gateway connection established
[21:23:13] [DEBUG] Shard ID 0 | Session ID: 5b88f99cc9e5ce42b055cdc846a77fb2 Trace: ['["gateway-prd-us-east1-b-g22j",{"micros":92370,"calls":["id_created",{"micros":2303,"calls":[]},"session_lookup_time",{"micros":315,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-prd-2-193",{"micros":88340,"calls":["start_session",{"micros":49171,"calls":["discord-api-6c869fb97d-fl4lt",{"micros":43918,"calls":["get_user",{"micros":8208},"get_guilds",{"micros":3736},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":429},"authorized_ip_coro",{"micros":9}]}]},"starting_guild_connect",{"micros":61,"calls":[]},"presence_started",{"micros":9896,"calls":[]},"guilds_started",{"micros":248,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":28932,"calls":[]},"connect_finished",{"micros":28938,"calls":[]},"build_ready",{"micros":23,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']
[21:23:13] [DEBUG] Dispatching Event: websocket_ready
[21:23:13] [DEBUG] Dispatching Event: guild_join
[21:23:13] [DEBUG] Dispatching Event: guild_join
[21:23:13] [DEBUG] Dispatching Event: guild_join
[21:23:13] [DEBUG] Dispatching Event: guild_join
[21:23:13] [DEBUG] Dispatching Event: guild_join
[21:23:13] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[21:23:13] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[21:23:13] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[21:23:13] [DEBUG] Waiting for bucket dd84d9818020c27975c0d5ab4a794d44 to unlock.
[21:23:14] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[21:23:14] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[21:23:14] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[21:23:14] [DEBUG] 0 is already up-to-date with 15 commands.
[21:23:14] [DEBUG] Sync of 1 scopes took 0.8099206999995658 seconds
[21:23:14] [DEBUG] Dispatching Event: startup
[21:23:14] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1703859794165, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[21:23:15] [DEBUG] 1174695146214928500::play should be called
[21:23:15] [DEBUG] Dispatching Event: message_create
[21:23:15] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[21:23:15] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE5MDI5ODk5NjA3MDE3MDYzNDpyaUlXN1J1SjZQRnBseXpKMERLUU95UlVMUHczUTlXWWtNUzdHZUFKVzFZdFdPYUNtS1pKT001ZnpybDI4SWNjeDAzTFlxUjJwQURQNjA1djdydHQ3ZzlKRmdpblFkOXJVdjdJWkdXN2Y1bWY5cTdOd004VndkTUFOMEJUaW9KbQ/callback Received 204 :: [4/5 calls remaining]
[21:23:15] [DEBUG] Sending data to websocket: {"op": 4, "d": {"guild_id": 1159832166998487050, "channel_id": 1159832166998487054, "self_mute": false, "self_deaf": false}}
[21:23:15] [DEBUG] Waiting for voice connection data...
[21:23:16] [DEBUG] Sending heartbeat every 41.25 seconds
[21:23:16] [DEBUG] Sending data to websocket: {"op": 1, "d": 9}
[21:23:16] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[21:23:16] [DEBUG] Dispatching Event: voice_user_join
[21:23:16] [DEBUG] Attempting to initialise voice gateway...
[21:23:16] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[21:23:16] [DEBUG] Voice Connection has identified itself to Voice Gateway
[21:23:16] [DEBUG] Discord send VC Ready! Establishing a socket connection...
[21:23:16] [DEBUG] IP Discovery in progress...
[21:23:16] [DEBUG] Voice Initial Response Received: b'\x00\x02\x00F\x00\x01\xd4\xa6171.227.96.41\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xceD'
[21:23:16] [DEBUG] IP Discovered: 171.227.96.41 #52804
[21:23:16] [DEBUG] Sending data to websocket: {"op": 1, "d": {"protocol": "udp", "data": {"address": "171.227.96.41", "port": 52804, "mode": "xsalsa20_poly1305_lite"}}}
[21:23:16] [DEBUG] Starting UDP Keep Alive
[21:23:16] [DEBUG] Unhandled OPCODE: 18 = data = {'user_id': '610841389164396565', 'flags': 2}
[21:23:16] [DEBUG] Unhandled OPCODE: 20 = data = {'user_id': '610841389164396565', 'platform': 0}
[21:23:16] [INFO] Voice connection established; using xsalsa20_poly1305_lite
[21:23:18] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[21:23:18] [DEBUG] PATCH /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5MDI5ODk5NjA3MDE3MDYzNDpyaUlXN1J1SjZQRnBseXpKMERLUU95UlVMUHczUTlXWWtNUzdHZUFKVzFZdFdPYUNtS1pKT001ZnpybDI4SWNjeDAzTFlxUjJwQURQNjA1djdydHQ3ZzlKRmdpblFkOXJVdjdJWkdXN2Y1bWY5cTdOd004VndkTUFOMEJUaW9KbQ/messages/{message_id} Received 200 :: [4/5 calls remaining]
[21:23:18] [DEBUG] Dispatching Event: message_create
[21:23:18] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[21:23:18] [DEBUG] POST /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5MDI5ODk5NjA3MDE3MDYzNDpyaUlXN1J1SjZQRnBseXpKMERLUU95UlVMUHczUTlXWWtNUzdHZUFKVzFZdFdPYUNtS1pKT001ZnpybDI4SWNjeDAzTFlxUjJwQURQNjA1djdydHQ3ZzlKRmdpblFkOXJVdjdJWkdXN2Y1bWY5cTdOd004VndkTUFOMEJUaW9KbQ Received 200 :: [4/5 calls remaining]
[21:23:22] [DEBUG] Sending heartbeat every 13.75 seconds
[21:23:22] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.3401257395458819}
[21:23:22] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:23:23] [DEBUG] ❤ Heartbeat acknowledged after 0.07459 seconds
[21:23:23] [DEBUG] Dispatching Event: message_create
[21:23:23] [DEBUG] Caching ingested rate limit data for: 3df15bae86f6647dd4dfcbd5c6949480
[21:23:23] [DEBUG] POST /channels/1159832166998487054/messages Received 200 :: [4/5 calls remaining]
[21:23:24] [DEBUG] Caching ingested rate limit data for: 3df15bae86f6647dd4dfcbd5c6949480
[21:23:24] [DEBUG] POST /channels/1159832166998487054/messages Received 200 :: [3/5 calls remaining]
[21:23:24] [DEBUG] Detected ffmpeg version: 2023-11-28-git-47e214245b-full_build-www.gyan.dev
[21:23:24] [DEBUG] Now playing <YTDownloader: https://rr4---sn-8pxuuxa-8j5r.googlevideo.com/videoplayback?expire=1703881400&ei=WNaOZZzWCv-h1d8PqLi40AU&ip=171.227.96.41&id=o-APjTMLSEhsWa2zoo3nwxYl7QtnDUv2TszNKWI9kYvVab&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=6B&mm=31%2C29&mn=sn-8pxuuxa-8j5r%2Csn-8pxuuxa-nbo6l&ms=au%2Crdu&mv=m&mvi=4&pl=21&initcwndbps=1807500&spc=UWF9f-_tVPUZ5bh4uJFf35ZcxEpuB1o&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=7887654&dur=431.161&lmt=1699749997146050&mt=1703859445&fvip=8&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgOrgdsxqyGRYia_AYn0DgpDUGTOyMVHBGGqWjtxU1sasCIAIhECaTfXJJHZmSpV_TPJzoKQh1eMXS7z5CdV3FMLPK&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRgIhAPUuB3Cx9FxpwjshISakgAAh3bbfg-_L41lfKODQ7fLMAiEAgXC95znatp70Tc7dr8cHNYn6XuSSFBetm-wOli26wvY%3D>
[21:23:25] [DEBUG] Dispatching Event: message_create
[21:23:28] [DEBUG] Dispatching Event: command_completion
[21:23:28] [INFO] Command Called: play with event.ctx.args = ['https://www.youtube.com/playlist?list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD'] | event.ctx.kwargs = {'song': 'https://www.youtube.com/playlist?list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD'}
[21:23:28] [DEBUG] 1190297750730981467::viewplaylist should be called
[21:23:28] [DEBUG] Dispatching Event: command_error
[21:23:28] [DEBUG] Dispatching Event: command_completion
[21:23:28] [DEBUG] Dispatching Event: error
[21:23:28] [INFO] Command Called: viewplaylist with event.ctx.args = [] | event.ctx.kwargs = {}
[21:23:28] [ERROR] Ignoring exception in cmd `/viewplaylist`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 802, in call_callback
    return await self.call_with_binding(callback, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\play.py", line 149, in _viewplaylist
    await paginator.send(ctx)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\ext\paginators.py", line 369, in send
    self._message = await ctx.send(**self.to_dict(), **kwargs)
                                     ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\ext\paginators.py", line 341, in to_dict
    page = self.pages[self.page_index]
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: list index out of range

[21:23:36] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.7354133841968516}
[21:23:36] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:23:36] [DEBUG] ❤ Heartbeat acknowledged after 0.07436 seconds
[21:23:50] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.7636834891807207}
[21:23:50] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:23:50] [DEBUG] ❤ Heartbeat acknowledged after 0.07268 seconds
[21:23:57] [DEBUG] Sending data to websocket: {"op": 1, "d": 15}
[21:23:57] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[21:23:57] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[21:24:04] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.945106089115368}
[21:24:04] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:24:04] [DEBUG] ❤ Heartbeat acknowledged after 0.07393 seconds
[21:24:17] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.9715424119859714}
[21:24:17] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:24:18] [DEBUG] ❤ Heartbeat acknowledged after 0.08119 seconds
[21:24:29] [DEBUG] Dispatching Event: message_create
[21:24:31] [DEBUG] Dispatching Event: error
[21:24:31] [ERROR] Ignoring exception in MessageCreate():
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 607, in _async_wrap
    await _coro(_event, *_args, **_kwargs)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 31, in __call__
    return await self.callback(self._binding, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\noi_chu.py", line 63, in on_message
    api_data = await response.json()
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1165, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.dictionaryapi.dev/api/v2/entries/en/')

[21:24:31] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.4886838506225145}
[21:24:31] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:24:31] [DEBUG] ❤ Heartbeat acknowledged after 0.07259 seconds
[21:24:38] [DEBUG] Sending data to websocket: {"op": 1, "d": 20}
[21:24:38] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[21:24:38] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[21:24:45] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.5073764567221449}
[21:24:45] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:24:45] [DEBUG] ❤ Heartbeat acknowledged after 0.07264 seconds
[21:24:47] [DEBUG] Dispatching Event: message_create
[21:24:49] [DEBUG] Dispatching Event: error
[21:24:49] [ERROR] Ignoring exception in MessageCreate():
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 607, in _async_wrap
    await _coro(_event, *_args, **_kwargs)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 31, in __call__
    return await self.callback(self._binding, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\noi_chu.py", line 63, in on_message
    api_data = await response.json()
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1165, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.dictionaryapi.dev/api/v2/entries/en/')

[21:24:59] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.836044717712278}
[21:24:59] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:24:59] [DEBUG] ❤ Heartbeat acknowledged after 0.07364 seconds
[21:25:12] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.7376590479295598}
[21:25:12] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:25:13] [DEBUG] ❤ Heartbeat acknowledged after 0.07310 seconds
[21:25:19] [DEBUG] Sending data to websocket: {"op": 1, "d": 22}
[21:25:19] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[21:25:20] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[21:25:26] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.7704335821480716}
[21:25:26] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:25:26] [DEBUG] ❤ Heartbeat acknowledged after 0.07517 seconds
[21:25:40] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.13539520571775454}
[21:25:40] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:25:40] [DEBUG] ❤ Heartbeat acknowledged after 0.07967 seconds
[21:25:54] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.2673567146498719}
[21:25:54] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:25:54] [DEBUG] ❤ Heartbeat acknowledged after 0.07437 seconds
[21:26:01] [DEBUG] Sending data to websocket: {"op": 1, "d": 22}
[21:26:01] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[21:26:01] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[21:26:08] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.3235012232830773}
[21:26:08] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:26:08] [DEBUG] ❤ Heartbeat acknowledged after 0.07384 seconds
[21:26:21] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.8807447140746235}
[21:26:21] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:26:21] [DEBUG] ❤ Heartbeat acknowledged after 0.07568 seconds
[21:26:35] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.5746043621242901}
[21:26:35] [DEBUG] ❤ Voice Connection is sending Heartbeat
[21:26:35] [DEBUG] ❤ Heartbeat acknowledged after 0.07461 seconds
[21:26:42] [DEBUG] Sending data to websocket: {"op": 1, "d": 22}
[21:26:42] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[21:26:42] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[21:26:43] [DEBUG] Dispatching Event: disconnect
[21:26:43] [DEBUG] Stopping the bot.
[21:26:43] [INFO] Shard ID 0 | Stopping Shard
