[11:31:33] [DEBUG] Running client sanity checks...
[11:31:33] [DEBUG] Loaded Extension: interactions.ext.jurigged
[11:31:34] [DEBUG] No setup function found in play
[11:31:34] [DEBUG] Found extension class Music in play: Attempting to load
[11:31:34] [DEBUG] Added callback: Music._menu
[11:31:34] [DEBUG] Added callback: Music._pause
[11:31:34] [DEBUG] Added callback: Music._resume
[11:31:34] [DEBUG] Added callback: Music._skip
[11:31:34] [DEBUG] Added callback: Music._skipto
[11:31:34] [DEBUG] Added callback: Music._stop
[11:31:34] [DEBUG] Added callback: Music._viewplaylist
[11:31:34] [DEBUG] Added callback: Music.play
[11:31:34] [DEBUG] Loaded Extension: play
[11:31:34] [DEBUG] No setup function found in askbard
[11:31:34] [DEBUG] Found extension class Bard in askbard: Attempting to load
[11:31:34] [DEBUG] Added callback: Bard._askbard
[11:31:34] [DEBUG] Added callback: Bard._endbard
[11:31:34] [DEBUG] Added callback: Bard.set_bard_channel
[11:31:34] [DEBUG] Loaded Extension: askbard
[11:31:34] [DEBUG] No setup function found in noi_chu
[11:31:34] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[11:31:34] [DEBUG] Added callback: NoiChu._reset
[11:31:34] [DEBUG] Added callback: NoiChu._world_setup
[11:31:34] [DEBUG] Loaded Extension: noi_chu
[11:31:34] [DEBUG] No setup function found in db_refesh
[11:31:34] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[11:31:34] [DEBUG] Loaded Extension: db_refesh
[11:31:34] [DEBUG] No setup function found in help
[11:31:34] [DEBUG] Found extension class Help in help: Attempting to load
[11:31:34] [DEBUG] Added callback: Help._about
[11:31:34] [DEBUG] Added callback: Help.help
[11:31:34] [DEBUG] Loaded Extension: help
[11:31:34] [DEBUG] No setup function found in channel_listen
[11:31:34] [DEBUG] Found extension class ChannelListen in channel_listen: Attempting to load
[11:31:34] [DEBUG] Added callback: ChannelListen._setup
[11:31:34] [DEBUG] Loaded Extension: channel_listen
[11:31:34] [DEBUG] Added callback: on_start
[11:31:34] [DEBUG] 1 callbacks have been loaded from __main__.
[11:31:34] [DEBUG] Added callback: _disconnect
[11:31:34] [DEBUG] Added callback: _on_websocket_ready
[11:31:34] [DEBUG] Added callback: on_autocomplete_completion
[11:31:34] [DEBUG] Added callback: on_autocomplete_error
[11:31:34] [DEBUG] Added callback: on_command_completion
[11:31:34] [DEBUG] Added callback: on_command_error
[11:31:34] [DEBUG] Added callback: on_component_completion
[11:31:34] [DEBUG] Added callback: on_component_error
[11:31:34] [DEBUG] Added callback: on_error
[11:31:34] [DEBUG] Added callback: on_modal_completion
[11:31:34] [DEBUG] Added callback: on_modal_error
[11:31:34] [DEBUG] Added callback: on_resume
[11:31:34] [DEBUG] 12 callbacks have been loaded from Client.
[11:31:34] [DEBUG] Attempting to login
[11:31:35] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[11:31:35] [DEBUG] GET /users/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:31:35] [DEBUG] GET /users/@me Received 200 :: [0/1000 calls remaining]
[11:31:35] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[11:31:35] [DEBUG] GET /oauth2/applications/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:31:35] [DEBUG] GET /oauth2/applications/@me Received 200 :: [0/1000 calls remaining]
[11:31:35] [WARNING] Setting sync_ext to True by default for syncing changes
[11:31:35] [INFO] Loading jurigged
[11:31:35] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\Main.py
[11:31:35] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\play.py
[11:31:35] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\embed.py
[11:31:35] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\askbard.py
[11:31:35] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\noi_chu.py
[11:31:35] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\db_refesh.py
[11:31:35] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\help.py
[11:31:35] [DEBUG] Watch D:\Project\Python\qpneruy-Git\music\channel_listen.py
[11:31:35] [DEBUG] GET /gateway Received 200 :: [1/1 calls remaining]
[11:31:35] [INFO] Shard ID 0 | Starting Shard
[11:31:35] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[11:31:36] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[11:31:36] [INFO] Shard ID 0 | Gateway connection established
[11:31:36] [DEBUG] Shard ID 0 | Session ID: 3dd68ac8be52f3bf4eae0fbdb4bb1104 Trace: ['["gateway-prd-us-east1-c-g6rs",{"micros":186395,"calls":["id_created",{"micros":1378,"calls":[]},"session_lookup_time",{"micros":5665,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-prd-2-80",{"micros":177931,"calls":["start_session",{"micros":127305,"calls":["discord-api-6c869fb97d-hgg65",{"micros":113810,"calls":["get_user",{"micros":9997},"get_guilds",{"micros":9120},"send_scheduled_deletion_message",{"micros":14},"guild_join_requests",{"micros":3248},"authorized_ip_coro",{"micros":15}]}]},"starting_guild_connect",{"micros":63,"calls":[]},"presence_started",{"micros":27284,"calls":[]},"guilds_started",{"micros":133,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":23117,"calls":[]},"connect_finished",{"micros":23122,"calls":[]},"build_ready",{"micros":21,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']
[11:31:36] [DEBUG] Dispatching Event: websocket_ready
[11:31:36] [DEBUG] Dispatching Event: guild_join
[11:31:36] [DEBUG] Dispatching Event: guild_join
[11:31:36] [DEBUG] Dispatching Event: guild_join
[11:31:36] [DEBUG] Dispatching Event: guild_join
[11:31:36] [DEBUG] Dispatching Event: guild_join
[11:31:37] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:31:37] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:31:37] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:31:37] [DEBUG] Waiting for bucket dd84d9818020c27975c0d5ab4a794d44 to unlock.
[11:31:37] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[11:31:37] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[11:31:37] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[11:31:37] [DEBUG] 0 is already up-to-date with 16 commands.
[11:31:37] [DEBUG] Sync of 1 scopes took 0.9707230000058189 seconds
[11:31:37] [DEBUG] Dispatching Event: startup
[11:31:37] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1704083497528, "activities": [{"name": "/help for helpful", "type": 0}], "status": "idle", "afk": false}}
[11:31:40] [DEBUG] 1174695146214928500::play should be called
[11:31:41] [DEBUG] Dispatching Event: message_create
[11:31:41] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[11:31:41] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE5MTIzNzI4NjY4ODQ1NjcxNDpJSktJbXZkb2tpMWU2NjVTN25SNk5uN2J3cmpMVmlRR1hkcnU3RGxtamRyWUx5N3J1R3E2d2JJN3JQbk9XcmFLYzUwSkRqNDdGMmhTcTk3QUFPT01lVXNBYzhnRnRubGJBckFjWFUxcHpUTlMzQzJDc1BicXNuQkptdUcyZEJZeA/callback Received 204 :: [4/5 calls remaining]
[11:31:41] [DEBUG] Sending data to websocket: {"op": 4, "d": {"guild_id": 1067024293709496340, "channel_id": 1191221610158497863, "self_mute": false, "self_deaf": false}}
[11:31:41] [DEBUG] Waiting for voice connection data...
[11:31:41] [DEBUG] Dispatching Event: voice_user_join
[11:31:42] [DEBUG] Attempting to initialise voice gateway...
[11:31:42] [DEBUG] Voice Connection has identified itself to Voice Gateway
[11:31:42] [DEBUG] Discord send VC Ready! Establishing a socket connection...
[11:31:42] [DEBUG] IP Discovery in progress...
[11:31:42] [DEBUG] Voice Initial Response Received: b'\x00\x02\x00F\x00\x03$\xb2171.227.96.41\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe7#'
[11:31:42] [DEBUG] IP Discovered: 171.227.96.41 #59171
[11:31:42] [DEBUG] Sending data to websocket: {"op": 1, "d": {"protocol": "udp", "data": {"address": "171.227.96.41", "port": 59171, "mode": "xsalsa20_poly1305_lite"}}}
[11:31:42] [DEBUG] Starting UDP Keep Alive
[11:31:42] [DEBUG] Unhandled OPCODE: 18 = data = {'user_id': '610841389164396565', 'flags': 2}
[11:31:42] [DEBUG] Unhandled OPCODE: 20 = data = {'user_id': '610841389164396565', 'platform': 0}
[11:31:42] [INFO] Voice connection established; using xsalsa20_poly1305_lite
[11:31:44] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[11:31:44] [DEBUG] PATCH /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5MTIzNzI4NjY4ODQ1NjcxNDpJSktJbXZkb2tpMWU2NjVTN25SNk5uN2J3cmpMVmlRR1hkcnU3RGxtamRyWUx5N3J1R3E2d2JJN3JQbk9XcmFLYzUwSkRqNDdGMmhTcTk3QUFPT01lVXNBYzhnRnRubGJBckFjWFUxcHpUTlMzQzJDc1BicXNuQkptdUcyZEJZeA/messages/{message_id} Received 200 :: [4/5 calls remaining]
[11:31:44] [DEBUG] Dispatching Event: message_create
[11:31:44] [DEBUG] Caching ingested rate limit data for: 3d2712a9e4fe17cc9d3fed4a8e672e5f
[11:31:44] [DEBUG] POST /webhooks/{application_id}/aW50ZXJhY3Rpb246MTE5MTIzNzI4NjY4ODQ1NjcxNDpJSktJbXZkb2tpMWU2NjVTN25SNk5uN2J3cmpMVmlRR1hkcnU3RGxtamRyWUx5N3J1R3E2d2JJN3JQbk9XcmFLYzUwSkRqNDdGMmhTcTk3QUFPT01lVXNBYzhnRnRubGJBckFjWFUxcHpUTlMzQzJDc1BicXNuQkptdUcyZEJZeA Received 200 :: [4/5 calls remaining]
[11:31:45] [DEBUG] Sending heartbeat every 13.75 seconds
[11:31:45] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.5837290011706854}
[11:31:45] [DEBUG] ❤ Voice Connection is sending Heartbeat
[11:31:46] [DEBUG] ❤ Heartbeat acknowledged after 0.03764 seconds
[11:31:48] [DEBUG] Dispatching Event: message_create
[11:31:48] [DEBUG] Caching ingested rate limit data for: 3df15bae86f6647dd4dfcbd5c6949480
[11:31:48] [DEBUG] POST /channels/1191221610158497863/messages Received 200 :: [4/5 calls remaining]
[11:31:50] [DEBUG] Caching ingested rate limit data for: 3df15bae86f6647dd4dfcbd5c6949480
[11:31:50] [DEBUG] POST /channels/1191221610158497863/messages Received 200 :: [3/5 calls remaining]
[11:31:50] [DEBUG] Detected ffmpeg version: 2023-11-28-git-47e214245b-full_build-www.gyan.dev
[11:31:50] [DEBUG] Now playing <YTDownloader: https://rr1---sn-8pxuuxa-8j5ls.googlevideo.com/videoplayback?expire=1704105106&ei=MkCSZaS0G4Sh0-kPj7mc2AY&ip=171.227.96.41&id=o-ACrwPwFhXy_RBQd1lx-zBZLTh3KmS0Zse4tTtS_Sd9Cb&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=1l&mm=31%2C29&mn=sn-8pxuuxa-8j5ls%2Csn-8pxuuxa-nbo6l&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=2098750&spc=UWF9f9mlLxThVe0cfGnzqNJfQwBoCOo&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3808759&dur=216.041&lmt=1699568995117037&mt=1704082866&fvip=7&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgDfbQ9vVqjCYXXC_hyQiH2IR1OSmSyh6Qwa9K6PMhtxUCIAeaLodp11Y0QbqvokHastWUl_zGj_31gBez0vDYll5G&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIgEePcVDhenKdihlx5qfgsaGzCe96_uP67ayJ3RXjLTDkCIQCqeZ3ITiOkbhTbwat1zxqsS4kpsubPRFLxM2YZiXa46A%3D%3D>
[11:31:50] [DEBUG] Dispatching Event: message_create
[11:31:52] [DEBUG] Dispatching Event: command_completion
[11:31:52] [INFO] Command Called: play with event.ctx.args = ['https://www.youtube.com/playlist?list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD'] | event.ctx.kwargs = {'song': 'https://www.youtube.com/playlist?list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD'}
[11:31:52] [DEBUG] 1190915528680800286::skipto should be called
[11:31:52] [DEBUG] Dispatching Event: command_error
[11:31:52] [DEBUG] Dispatching Event: command_completion
[11:31:52] [DEBUG] Dispatching Event: error
[11:31:52] [INFO] Command Called: skipto with event.ctx.args = [3] | event.ctx.kwargs = {'index': 3}
[11:31:52] [ERROR] Ignoring exception in cmd `/skipto`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\play.py", line 109, in _skipto
    await music_player.skipto(index)
  File "D:\Project\Python\qpneruy-Git\modules\Music_queue.py", line 223, in skipto
    await self.voice_state.ws.run()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\voice\voice_gateway.py", line 85, in run
    msg = await receiving
          ^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\voice\voice_gateway.py", line 110, in receive
    resp = await self.ws.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_ws.py", line 232, in receive
    raise RuntimeError("Concurrent call to receive() is not allowed")
RuntimeError: Concurrent call to receive() is not allowed

[11:31:52] [DEBUG] Sending heartbeat every 41.25 seconds
[11:31:52] [DEBUG] Sending data to websocket: {"op": 1, "d": 15}
[11:31:52] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[11:31:53] [DEBUG] Dispatching Event: message_create
[11:31:53] [DEBUG] Caching ingested rate limit data for: 3df15bae86f6647dd4dfcbd5c6949480
[11:31:53] [DEBUG] POST /channels/1191221610158497863/messages Received 200 :: [4/5 calls remaining]
[11:31:53] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[11:31:53] [DEBUG] Dispatching Event: message_create
[11:31:53] [DEBUG] Caching ingested rate limit data for: 3df15bae86f6647dd4dfcbd5c6949480
[11:31:53] [DEBUG] POST /channels/1191221610158497863/messages Received 200 :: [3/5 calls remaining]
[11:31:53] [DEBUG] Detected ffmpeg version: 2023-11-28-git-47e214245b-full_build-www.gyan.dev
[11:31:53] [DEBUG] Now playing <YTDownloader: https://rr1---sn-8pxuuxa-8j5ek.googlevideo.com/videoplayback?expire=1704105111&ei=N0CSZZPrK9eg0-kPz_-uiA8&ip=171.227.96.41&id=o-ANWCPve3wo_FHXFF9E9DdNFZ6ScmO7WFnpZEIx2iTpbW&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=fx&mm=31%2C29&mn=sn-8pxuuxa-8j5ek%2Csn-8pxuuxa-nboer&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1621250&spc=UWF9fwD_LZRAIs3FzIb3hS5HNPQxy70&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3907398&dur=228.761&lmt=1701812167991333&mt=1704082866&fvip=7&keepalive=yes&fexp=24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAN0KU311-P1XzCe5-q5yqolZx2xA_aS8nohK6Ok4HN6uAiEAhaqWM9ULAmPPSxE1Bvv7LLKZmfaisPtTaQRZrSkprM4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIgV9WmysqLEVqHjIx8mTP1ksLXc5MjxEMVExXmFpKFengCIQDqUMvGUa1Zk704FyBDVj6wa3IEbD5Grb0X5rlxblB1Lw%3D%3D>
[11:31:54] [DEBUG] 1190915528680800286::skipto should be called
[11:31:54] [DEBUG] Dispatching Event: command_error
[11:31:54] [DEBUG] Dispatching Event: command_completion
[11:31:54] [DEBUG] Dispatching Event: error
[11:31:54] [INFO] Command Called: skipto with event.ctx.args = [3] | event.ctx.kwargs = {'index': 3}
[11:31:54] [ERROR] Ignoring exception in cmd `/skipto`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\play.py", line 109, in _skipto
    await music_player.skipto(index)
  File "D:\Project\Python\qpneruy-Git\modules\Music_queue.py", line 223, in skipto
    await self.voice_state.ws.run()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\voice\voice_gateway.py", line 85, in run
    msg = await receiving
          ^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\voice\voice_gateway.py", line 110, in receive
    resp = await self.ws.receive()
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'receive'

[11:31:54] [DEBUG] Dispatching Event: message_create
[11:31:54] [DEBUG] Caching ingested rate limit data for: 3df15bae86f6647dd4dfcbd5c6949480
[11:31:54] [DEBUG] POST /channels/1191221610158497863/messages Received 200 :: [3/5 calls remaining]
[11:31:55] [DEBUG] Dispatching Event: message_create
[11:31:55] [DEBUG] Caching ingested rate limit data for: 3df15bae86f6647dd4dfcbd5c6949480
[11:31:55] [DEBUG] POST /channels/1191221610158497863/messages Received 200 :: [3/5 calls remaining]
[11:31:55] [DEBUG] Detected ffmpeg version: 2023-11-28-git-47e214245b-full_build-www.gyan.dev
[11:31:55] [DEBUG] Now playing <YTDownloader: https://rr1---sn-8pxuuxa-8j5ek.googlevideo.com/videoplayback?expire=1704105111&ei=N0CSZZPrK9eg0-kPz_-uiA8&ip=171.227.96.41&id=o-ANWCPve3wo_FHXFF9E9DdNFZ6ScmO7WFnpZEIx2iTpbW&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=fx&mm=31%2C29&mn=sn-8pxuuxa-8j5ek%2Csn-8pxuuxa-nboer&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1621250&spc=UWF9fwD_LZRAIs3FzIb3hS5HNPQxy70&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3907398&dur=228.761&lmt=1701812167991333&mt=1704082866&fvip=7&keepalive=yes&fexp=24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAN0KU311-P1XzCe5-q5yqolZx2xA_aS8nohK6Ok4HN6uAiEAhaqWM9ULAmPPSxE1Bvv7LLKZmfaisPtTaQRZrSkprM4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIgV9WmysqLEVqHjIx8mTP1ksLXc5MjxEMVExXmFpKFengCIQDqUMvGUa1Zk704FyBDVj6wa3IEbD5Grb0X5rlxblB1Lw%3D%3D>
[11:31:57] [DEBUG] Ending UDP Keep Alive
[11:31:58] [DEBUG] 1190915528680800286::skipto should be called
[11:31:58] [DEBUG] Dispatching Event: command_error
[11:31:58] [DEBUG] Dispatching Event: command_completion
[11:31:58] [DEBUG] Dispatching Event: error
[11:31:58] [INFO] Command Called: skipto with event.ctx.args = [3] | event.ctx.kwargs = {'index': 3}
[11:31:58] [ERROR] Ignoring exception in cmd `/skipto`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\play.py", line 109, in _skipto
    await music_player.skipto(index)
  File "D:\Project\Python\qpneruy-Git\modules\Music_queue.py", line 223, in skipto
    await self.voice_state.ws.run()
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\voice\voice_gateway.py", line 85, in run
    msg = await receiving
          ^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\api\voice\voice_gateway.py", line 110, in receive
    resp = await self.ws.receive()
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'receive'

[11:32:11] [DEBUG] Dispatching Event: disconnect
[11:32:11] [DEBUG] Stopping the bot.
[11:32:11] [INFO] Shard ID 0 | Stopping Shard
