[18:40:20] [DEBUG] Running client sanity checks...
[18:40:21] [DEBUG] No setup function found in play
[18:40:21] [DEBUG] Found extension class Music in play: Attempting to load
[18:40:21] [DEBUG] Added callback: Music._menu
[18:40:21] [DEBUG] Added callback: Music._pause
[18:40:21] [DEBUG] Added callback: Music._resume
[18:40:21] [DEBUG] Added callback: Music._skip
[18:40:21] [DEBUG] Added callback: Music._stop
[18:40:21] [DEBUG] Added callback: Music.play
[18:40:21] [DEBUG] Loaded Extension: play
[18:40:22] [DEBUG] No setup function found in askbard
[18:40:22] [DEBUG] Found extension class Bard in askbard: Attempting to load
[18:40:22] [DEBUG] Added callback: Bard._askbard
[18:40:22] [DEBUG] Added callback: Bard._endbard
[18:40:22] [DEBUG] Added callback: Bard.set_bard_channel
[18:40:22] [DEBUG] Loaded Extension: askbard
[18:40:22] [DEBUG] No setup function found in noi_chu
[18:40:22] [DEBUG] Found extension class NoiChu in noi_chu: Attempting to load
[18:40:22] [DEBUG] Added callback: NoiChu._reset
[18:40:22] [DEBUG] Added callback: NoiChu._world_setup
[18:40:22] [DEBUG] Loaded Extension: noi_chu
[18:40:22] [DEBUG] No setup function found in db_refesh
[18:40:22] [DEBUG] Found extension class Database in db_refesh: Attempting to load
[18:40:22] [DEBUG] Loaded Extension: db_refesh
[18:40:22] [DEBUG] No setup function found in help
[18:40:22] [DEBUG] Found extension class Help in help: Attempting to load
[18:40:22] [DEBUG] Added callback: Help.help
[18:40:22] [DEBUG] Loaded Extension: help
[18:40:22] [DEBUG] Added callback: __join
[18:40:22] [DEBUG] Added callback: __leave
[18:40:22] [DEBUG] Added callback: _about
[18:40:22] [DEBUG] Added callback: _refresh
[18:40:22] [DEBUG] Added callback: _setup
[18:40:22] [DEBUG] Added callback: on_start
[18:40:22] [DEBUG] 6 callbacks have been loaded from __main__.
[18:40:22] [DEBUG] Added callback: _disconnect
[18:40:22] [DEBUG] Added callback: _on_websocket_ready
[18:40:22] [DEBUG] Added callback: on_autocomplete_completion
[18:40:22] [DEBUG] Added callback: on_autocomplete_error
[18:40:22] [DEBUG] Added callback: on_command_completion
[18:40:22] [DEBUG] Added callback: on_command_error
[18:40:22] [DEBUG] Added callback: on_component_completion
[18:40:22] [DEBUG] Added callback: on_component_error
[18:40:22] [DEBUG] Added callback: on_error
[18:40:22] [DEBUG] Added callback: on_modal_completion
[18:40:22] [DEBUG] Added callback: on_modal_error
[18:40:22] [DEBUG] Added callback: on_resume
[18:40:22] [DEBUG] 12 callbacks have been loaded from Client.
[18:40:22] [DEBUG] Attempting to login
[18:40:22] [DEBUG] Caching ingested rate limit data for: 78bb8553d9352a5a2f89f9def401287a
[18:40:22] [DEBUG] GET /users/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[18:40:22] [DEBUG] GET /users/@me Received 200 :: [0/1000 calls remaining]
[18:40:23] [DEBUG] Caching ingested rate limit data for: d28a133af187e91d71d96a223467ce49
[18:40:23] [DEBUG] GET /oauth2/applications/@me Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[18:40:23] [DEBUG] GET /oauth2/applications/@me Received 200 :: [0/1000 calls remaining]
[18:40:23] [DEBUG] GET /gateway Received 200 :: [1/1 calls remaining]
[18:40:23] [INFO] Shard ID 0 | Starting Shard
[18:40:23] [INFO] Shard ID 0 | Shard is attempting to connect to gateway...
[18:40:23] [DEBUG] Shard ID 0 | Identification payload sent to gateway, requesting intents: 3407613
[18:40:24] [INFO] Shard ID 0 | Gateway connection established
[18:40:24] [DEBUG] Shard ID 0 | Session ID: 1a95dc41e15b40b83c738df34b2098ac Trace: ['["gateway-prd-us-east1-d-c36b",{"micros":148261,"calls":["id_created",{"micros":1736,"calls":[]},"session_lookup_time",{"micros":2271,"calls":[]},"session_lookup_finished",{"micros":12,"calls":[]},"discord-sessions-prd-2-57",{"micros":143812,"calls":["start_session",{"micros":104998,"calls":["discord-api-74b789ff84-pr7td",{"micros":95209,"calls":["get_user",{"micros":11870},"get_guilds",{"micros":15731},"send_scheduled_deletion_message",{"micros":13},"guild_join_requests",{"micros":255},"authorized_ip_coro",{"micros":15}]}]},"starting_guild_connect",{"micros":67,"calls":[]},"presence_started",{"micros":358,"calls":[]},"guilds_started",{"micros":180,"calls":[]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":38186,"calls":[]},"connect_finished",{"micros":38191,"calls":[]},"build_ready",{"micros":16,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}]']
[18:40:24] [DEBUG] Dispatching Event: websocket_ready
[18:40:24] [DEBUG] Dispatching Event: guild_join
[18:40:24] [DEBUG] Dispatching Event: guild_join
[18:40:24] [DEBUG] Dispatching Event: guild_join
[18:40:24] [DEBUG] Dispatching Event: guild_join
[18:40:24] [DEBUG] Dispatching Event: guild_join
[18:40:24] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[18:40:24] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[18:40:24] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[18:40:24] [DEBUG] Waiting for bucket dd84d9818020c27975c0d5ab4a794d44 to unlock.
[18:40:24] [DEBUG] Caching ingested rate limit data for: dd84d9818020c27975c0d5ab4a794d44
[18:40:24] [DEBUG] GET /applications/{application_id}/commands Has exhausted its ratelimit (1000)! Locking route for 0.001 seconds
[18:40:24] [DEBUG] GET /applications/{application_id}/commands Received 200 :: [0/1000 calls remaining]
[18:40:24] [INFO] Overwriting 0 with 15 application commands
[18:40:25] [DEBUG] Caching ingested rate limit data for: 3e32a240d3716487d7d8f6dae6c54f6b
[18:40:25] [DEBUG] PUT /applications/{app_id}/commands Received 200 :: [1/2 calls remaining]
[18:40:25] [DEBUG] Sync of 1 scopes took 1.199132900001132 seconds
[18:40:25] [DEBUG] Dispatching Event: startup
[18:40:25] [DEBUG] Sending data to websocket: {"op": 3, "d": {"since": 1702640425448, "activities": [{"name": "l\u1ec7nh /help \u0111\u1ec3 gi\u00fap \u0111\u1ee1", "type": 0}], "status": "idle", "afk": false}}
[18:40:38] [DEBUG] Sending heartbeat every 41.25 seconds
[18:40:38] [DEBUG] Sending data to websocket: {"op": 1, "d": 6}
[18:40:38] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[18:40:39] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[18:40:41] [DEBUG] Dispatching Event: voice_user_join
[18:40:43] [DEBUG] Caching ingested rate limit data for: be56019ae011689ff5baf218062aacf5
[18:40:43] [DEBUG] POST /guilds/1067024293709496340/channels Received 201 :: [1999/2000 calls remaining]
[18:40:44] [DEBUG] Caching ingested rate limit data for: 6e836da6cef38ba2f3dfd8568a4e9631
[18:40:44] [DEBUG] PATCH /channels/1185184661798924320 Received 200 :: [9/10 calls remaining]
[18:40:44] [DEBUG] Shard ID 0 | No processor for `raw_channel_topic_update`
[18:40:44] [DEBUG] Shard ID 0 | No processor for `raw_voice_channel_status_update`
[18:40:44] [DEBUG] Caching ingested rate limit data for: c7f060a5d9790cb6f53000110a7b7edf
[18:40:44] [DEBUG] PATCH /guilds/1067024293709496340/members/{user_id} Received 200 :: [9/10 calls remaining]
[18:40:48] [DEBUG] 1174695146214928500::play should be called
[18:40:49] [DEBUG] Dispatching Event: message_create
[18:40:49] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[18:40:49] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE4NTE4NDY4MzI0ODU4Njc1MjpzNWpPTHdIWmMzR0dTY05NUmxOOXFXcFdZTHlHWmxXb0k0eDZpbGR4ZWIxZnRwT1g5bWxUZ2VKUXlOd2RyR29qSVkyZzhVMEl4bWlLckZwOEVrUFd0RzFJZUl1VWZqSEtiY3YzZFducUNKZDFvZDA5TnhoclNteHdITjhLek9FYg/callback Received 204 :: [4/5 calls remaining]
[18:40:49] [DEBUG] Sending data to websocket: {"op": 4, "d": {"guild_id": 1067024293709496340, "channel_id": 1185184661798924320, "self_mute": false, "self_deaf": false}}
[18:40:49] [DEBUG] Waiting for voice connection data...
[18:40:49] [DEBUG] Dispatching Event: voice_user_join
[18:40:49] [DEBUG] Attempting to initialise voice gateway...
[18:40:50] [DEBUG] Voice Connection has identified itself to Voice Gateway
[18:40:50] [DEBUG] Discord send VC Ready! Establishing a socket connection...
[18:40:50] [DEBUG] IP Discovery in progress...
[18:40:50] [DEBUG] Voice Initial Response Received: b'\x00\x02\x00F\x00\x00\x0cb171.227.103.111\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x89'
[18:40:50] [DEBUG] IP Discovered: 171.227.103.111 #65417
[18:40:50] [DEBUG] Sending data to websocket: {"op": 1, "d": {"protocol": "udp", "data": {"address": "171.227.103.111", "port": 65417, "mode": "xsalsa20_poly1305_lite"}}}
[18:40:50] [DEBUG] Starting UDP Keep Alive
[18:40:50] [DEBUG] Unhandled OPCODE: 18 = data = {'user_id': '610841389164396565', 'flags': 2}
[18:40:50] [DEBUG] Unhandled OPCODE: 20 = data = {'user_id': '610841389164396565', 'platform': 0}
[18:40:50] [INFO] Voice connection established; using xsalsa20_poly1305_lite
[18:40:51] [DEBUG] Dispatching Event: command_error
[18:40:51] [DEBUG] Dispatching Event: command_completion
[18:40:51] [DEBUG] Dispatching Event: error
[18:40:51] [INFO] Command Called: play with event.ctx.args = ['https://www.youtube.com/watch?v=yK5LEzw35vU&list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD&index=2'] | event.ctx.kwargs = {'song': 'https://www.youtube.com/watch?v=yK5LEzw35vU&list=PLL-LXY9dtjAYgBX0TiNDwAbgThsGBb8jD&index=2'}
[18:40:51] [ERROR] Ignoring exception in cmd `/play`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\play.py", line 92, in play
    await music_queues.put(audio, avatar_url)
  File "D:\Project\Python\qpneruy-Git\modules\Music_queue.py", line 31, in put
    title = audio_d.entry['title']
            ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'title'

[18:40:55] [DEBUG] Sending heartbeat every 13.75 seconds
[18:40:55] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.10343001585101963}
[18:40:55] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:40:55] [DEBUG] ❤ Heartbeat acknowledged after 0.06815 seconds
[18:41:08] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.15055032962742054}
[18:41:08] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:41:09] [DEBUG] ❤ Heartbeat acknowledged after 0.06753 seconds
[18:41:20] [DEBUG] Sending data to websocket: {"op": 1, "d": 19}
[18:41:20] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[18:41:20] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[18:41:22] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.8637932361344276}
[18:41:22] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:41:22] [DEBUG] ❤ Heartbeat acknowledged after 0.06772 seconds
[18:41:36] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.26551253697158395}
[18:41:36] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:41:36] [DEBUG] ❤ Heartbeat acknowledged after 0.06695 seconds
[18:41:50] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.8692484974972384}
[18:41:50] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:41:50] [DEBUG] ❤ Heartbeat acknowledged after 0.06986 seconds
[18:42:01] [DEBUG] Sending data to websocket: {"op": 1, "d": 19}
[18:42:01] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[18:42:01] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[18:42:04] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.6303682019761563}
[18:42:04] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:42:04] [DEBUG] ❤ Heartbeat acknowledged after 0.07492 seconds
[18:42:17] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.4689084875757722}
[18:42:17] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:42:17] [DEBUG] ❤ Heartbeat acknowledged after 0.06792 seconds
[18:42:27] [DEBUG] 1174695146214928500::play should be called
[18:42:27] [DEBUG] Dispatching Event: message_create
[18:42:27] [DEBUG] Caching ingested rate limit data for: 432f6223265d156004ac81366c5a948f
[18:42:27] [DEBUG] POST /interactions/{interaction_id}/aW50ZXJhY3Rpb246MTE4NTE4NTA5NjE2NTIyODU4NDpMazZjUnUwYlpXUzJQYmRHWFpDWFFQdHRQaHNyZlE2Rm8zOXVwZWJBTEVkeFVJbTJHMXZrZ3J6NDEweWZmTGlBamNWZTB2bWJ0a2Q3cUU3aGFDUzlVemVvc3VJalFPaG15dFVRSFJMblNNR3kyalhXbncwdm4xRlVGQ2hFU3ZUOA/callback Received 204 :: [4/5 calls remaining]
[18:42:28] [DEBUG] Dispatching Event: command_error
[18:42:28] [DEBUG] Dispatching Event: command_completion
[18:42:28] [DEBUG] Dispatching Event: error
[18:42:28] [INFO] Command Called: play with event.ctx.args = ['nụ cười'] | event.ctx.kwargs = {'song': 'nụ cười'}
[18:42:28] [ERROR] Ignoring exception in cmd `/play`:
Traceback (most recent call last):
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1900, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\client\client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huuti\AppData\Local\Programs\Python\Python311\Lib\site-packages\interactions\models\internal\callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\play.py", line 91, in play
    avatar_url = self.get_uploader_avatar(audio)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Python\qpneruy-Git\music\play.py", line 68, in get_uploader_avatar
    url_video = f'https://www.youtube.com/watch?v={audio_d.entry["id"]}'
                                                   ~~~~~~~~~~~~~^^^^^^
KeyError: 'id'

[18:42:31] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.4658110366545596}
[18:42:31] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:42:31] [DEBUG] ❤ Heartbeat acknowledged after 0.06871 seconds
[18:42:42] [DEBUG] Sending data to websocket: {"op": 1, "d": 21}
[18:42:42] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[18:42:42] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[18:42:45] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.2538313281638157}
[18:42:45] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:42:45] [DEBUG] ❤ Heartbeat acknowledged after 0.06829 seconds
[18:42:59] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.6420748305871978}
[18:42:59] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:42:59] [DEBUG] ❤ Heartbeat acknowledged after 0.06870 seconds
[18:43:12] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.27260618162873573}
[18:43:12] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:43:12] [DEBUG] ❤ Heartbeat acknowledged after 0.06862 seconds
[18:43:23] [DEBUG] Sending data to websocket: {"op": 1, "d": 21}
[18:43:23] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[18:43:24] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[18:43:26] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.3970199666830414}
[18:43:26] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:43:26] [DEBUG] ❤ Heartbeat acknowledged after 0.06810 seconds
[18:43:40] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.6825741344714621}
[18:43:40] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:43:40] [DEBUG] ❤ Heartbeat acknowledged after 0.06813 seconds
[18:43:54] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.5944764614317326}
[18:43:54] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:43:54] [DEBUG] ❤ Heartbeat acknowledged after 0.06757 seconds
[18:44:05] [DEBUG] Sending data to websocket: {"op": 1, "d": 21}
[18:44:05] [DEBUG] Shard ID 0 | ❤ Gateway is sending a Heartbeat
[18:44:05] [DEBUG] Shard ID 0 | ❤ Received heartbeat acknowledgement from gateway
[18:44:07] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.8643858843346237}
[18:44:07] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:44:07] [DEBUG] ❤ Heartbeat acknowledged after 0.07271 seconds
[18:44:21] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.7704674905215801}
[18:44:21] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:44:21] [DEBUG] ❤ Heartbeat acknowledged after 0.07535 seconds
[18:44:35] [DEBUG] Sending data to websocket: {"op": 3, "d": 0.7155018931305009}
[18:44:35] [DEBUG] ❤ Voice Connection is sending Heartbeat
[18:44:35] [DEBUG] ❤ Heartbeat acknowledged after 0.06759 seconds
[18:44:40] [DEBUG] Dispatching Event: disconnect
[18:44:40] [DEBUG] Stopping the bot.
[18:44:40] [INFO] Shard ID 0 | Stopping Shard
